apiVersion: v1
kind: Pod
metadata:
  name: books-ms-pod
  labels:
    type: service
spec:
  containers:
  - name: books-ms-db
    image: mongo
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: books-ms-storage
      mountPath: /data/db
  - name: books-ms
    image: vfarcic/books-ms
    ports:
    - containerPort: 8080
  volumes:
  - name: books-ms-storage
    emptyDir: {}
